// Advertising recommendations.
//
// Two signal sources:
//   1. CategoryIntel (platform-wide) — ad budget recommendations per category
//   2. MerchantIntelSummary.topWilayas — per-merchant regional ad focus

import type { CategoryIntel } from "@/lib/merchant-intelligence/types";
import type { MerchantIntelSummary } from "@/lib/merchant-intelligence/types";
import type { Recommendation } from "./types";
import { calculateConfidence, rateSignalStrength } from "./scoring";
import {
  adPauseSavings,
  adReduceSavings,
  adIncreaseRevenue,
  regionFocusRevenue,
} from "./financial-impact";

let _id = 0;
function nextId(): string {
  return `adv-${++_id}`;
}

export function resetAdvertisingIds(): void {
  _id = 0;
}

const NOW = new Date().toISOString();

// ── Thresholds ────────────────────────────────────────────────────────────────

const MIN_ORDERS_CATEGORY = 10;
const MIN_ORDERS_WILAYA   = 5;

const SUCCESS_INCREASE_THRESHOLD = 0.72;
const SUCCESS_MAINTAIN_LOW       = 0.55;
const SUCCESS_REDUCE_THRESHOLD   = 0.38;
// Below REDUCE → pause

const WILAYA_FOCUS_GOOD = 0.75;  // Wilaya worth focusing ads on
const WILAYA_AVOID_BAD  = 0.35;  // Wilaya to reduce/stop ads in

// ── Category-level advertising recommendations (platform-wide) ────────────────

export function generateCategoryAdvertisingRecommendations(
  categories: CategoryIntel[],
): Recommendation[] {
  const recs: Recommendation[] = [];

  for (const cat of categories) {
    if (cat.totalOrders < MIN_ORDERS_CATEGORY) continue;

    const rate = cat.deliverySuccessRate;

    if (cat.adRecommendation === "pause") {
      const signal = rateSignalStrength(rate, SUCCESS_MAINTAIN_LOW, SUCCESS_REDUCE_THRESHOLD);
      const confidence = calculateConfidence(cat.totalOrders, signal);
      const savings = adPauseSavings(cat.returnedOrders + cat.refusedOrders, cat.avgOrderValueDzd);
      recs.push({
        id: nextId(),
        merchantId: null,
        merchantName: null,
        category: "advertising",
        type: "advertising_pause",
        priority: rate < 0.25 ? "CRITICAL" : "HIGH",
        title: `Pause advertising for category "${cat.categoryName}"`,
        description: `Delivery success rate is only ${(rate * 100).toFixed(1)}% across ${cat.totalOrders.toLocaleString()} orders. ${(cat.returnedOrders + cat.refusedOrders).toLocaleString()} orders were returned or refused. Continuing ad spend amplifies losses.`,
        reason: `Success rate of ${(rate * 100).toFixed(1)}% is below the ${(SUCCESS_REDUCE_THRESHOLD * 100).toFixed(0)}% threshold. Every new order generated by ads in this category has a high probability of being returned, wasting ad budget and logistics costs.`,
        businessImpact: `Category gross revenue: ${(cat.grossRevenueDzd / 1000).toFixed(0)}K DZD. With ${(rate * 100).toFixed(1)}% success rate, the effective revenue after returns is significantly lower. Pausing prevents further losses.`,
        estimatedSavingsDzd: savings,
        estimatedRevenueIncreaseDzd: 0,
        confidenceScore: confidence,
        generatedAt: NOW,
        requiredDataSources: ["marketing_product_order_lines"],
        recommendedActions: [
          { label: "Pause all ad campaigns in this category", description: "Stop active ad spend until root cause of high return rate is resolved." },
          { label: "Investigate return reasons", description: `Best-performing wilaya: ${cat.topWilayas[0]?.wilaya ?? "N/A"}. Worst: ${cat.worstWilayas[0]?.wilaya ?? "N/A"}. Compare these markets.` },
          { label: "Review product descriptions and images", description: "High returns often indicate expectation mismatch at delivery." },
        ],
        categoryName: cat.categoryName,
      });
    }

    if (cat.adRecommendation === "reduce") {
      const signal = rateSignalStrength(rate, SUCCESS_MAINTAIN_LOW, SUCCESS_REDUCE_THRESHOLD);
      const confidence = calculateConfidence(cat.totalOrders, signal);
      const savings = adReduceSavings(cat.returnedOrders + cat.refusedOrders, cat.avgOrderValueDzd);
      recs.push({
        id: nextId(),
        merchantId: null,
        merchantName: null,
        category: "advertising",
        type: "advertising_reduce",
        priority: "MEDIUM",
        title: `Reduce advertising budget for category "${cat.categoryName}"`,
        description: `Delivery success rate is ${(rate * 100).toFixed(1)}% — below the 55% maintain threshold. ${cat.totalOrders.toLocaleString()} total orders with ${(cat.returnedOrders + cat.refusedOrders).toLocaleString()} returns/refusals. Return losses are eroding margins.`,
        reason: `Success rate of ${(rate * 100).toFixed(1)}% is in the 38–55% range where ad spend generates orders that often don't convert to collected revenue. Reducing spend by 30–50% limits downside risk.`,
        businessImpact: `Reducing returns by ${(adReduceSavings(cat.returnedOrders + cat.refusedOrders, cat.avgOrderValueDzd) / 1000).toFixed(0)}K DZD is achievable by cutting ad spend on the lowest-performing wilayas within this category.`,
        estimatedSavingsDzd: savings,
        estimatedRevenueIncreaseDzd: 0,
        confidenceScore: confidence,
        generatedAt: NOW,
        requiredDataSources: ["marketing_product_order_lines"],
        recommendedActions: [
          { label: "Reduce budget by 30–50%", description: "Focus remaining budget on wilayas with above-average success rates." },
          { label: "Exclude worst-performing wilayas", description: `Worst wilaya: ${cat.worstWilayas[0]?.wilaya ?? "N/A"} with ${(cat.worstWilayas[0] ? cat.worstWilayas[0].successRate * 100 : 0).toFixed(1)}% success rate.` },
          { label: "Monitor recovery", description: "Re-evaluate after 30 days of reduced spend." },
        ],
        categoryName: cat.categoryName,
      });
    }

    if (cat.adRecommendation === "increase") {
      const signal = rateSignalStrength(rate, SUCCESS_INCREASE_THRESHOLD, SUCCESS_MAINTAIN_LOW);
      const confidence = calculateConfidence(cat.totalOrders, signal);
      const revenue = adIncreaseRevenue(cat.deliveredOrders, cat.avgOrderValueDzd);
      recs.push({
        id: nextId(),
        merchantId: null,
        merchantName: null,
        category: "advertising",
        type: "advertising_increase",
        priority: rate >= 0.85 ? "HIGH" : "MEDIUM",
        title: `Increase advertising budget for category "${cat.categoryName}"`,
        description: `Delivery success rate is ${(rate * 100).toFixed(1)}% across ${cat.totalOrders.toLocaleString()} orders. This category has strong market fit. Scaling ad spend is expected to generate proportional revenue increase.`,
        reason: `Success rate of ${(rate * 100).toFixed(1)}% is above the ${(SUCCESS_INCREASE_THRESHOLD * 100).toFixed(0)}% increase threshold. More orders in this category produce reliable delivered revenue.`,
        businessImpact: `Each additional 100 orders in this category should yield approximately ${(cat.deliveredOrders > 0 ? (cat.avgOrderValueDzd * (cat.deliveredOrders / cat.totalOrders) * 100 / 1000).toFixed(0) : 0)}K DZD delivered revenue.`,
        estimatedSavingsDzd: 0,
        estimatedRevenueIncreaseDzd: revenue,
        confidenceScore: confidence,
        generatedAt: NOW,
        requiredDataSources: ["marketing_product_order_lines"],
        recommendedActions: [
          { label: "Increase ad budget by 20–40%", description: "Scale spend proportionally while monitoring return rate." },
          { label: "Focus on top wilayas", description: `Best-performing wilaya: ${cat.topWilayas[0]?.wilaya ?? "N/A"} (${cat.topWilayas[0] ? (cat.topWilayas[0].successRate * 100).toFixed(1) : "—"}% success rate).` },
          { label: "Track incremental ROAS", description: "Measure return on ad spend week-by-week as budget increases." },
        ],
        categoryName: cat.categoryName,
      });
    }
  }

  return recs;
}

// ── Per-merchant wilaya advertising recommendations ────────────────────────────

export function generateMerchantWilayaAdvertisingRecommendations(
  summaries: MerchantIntelSummary[],
): Recommendation[] {
  const recs: Recommendation[] = [];

  for (const m of summaries) {
    if (m.topWilayas.length === 0) continue;

    // Find best and worst wilayas for this merchant
    const sorted = [...m.topWilayas].sort((a, b) => b.successRate - a.successRate);
    const bestWilayas = sorted.filter(
      (w) => w.successRate >= WILAYA_FOCUS_GOOD && w.orders >= MIN_ORDERS_WILAYA,
    );
    const worstWilayas = sorted.filter(
      (w) => w.successRate <= WILAYA_AVOID_BAD && w.orders >= MIN_ORDERS_WILAYA,
    );

    // Focus recommendation for best wilayas
    if (bestWilayas.length > 0) {
      const best = bestWilayas[0];
      const signal = rateSignalStrength(best.successRate, WILAYA_FOCUS_GOOD, 0.5);
      const confidence = calculateConfidence(best.orders, signal);
      const revenue = regionFocusRevenue(best.orders, m.avgBasketDzd);
      recs.push({
        id: nextId(),
        merchantId: m.merchantId,
        merchantName: m.name,
        category: "advertising",
        type: "advertising_region_focus",
        priority: "MEDIUM",
        title: `Focus ${m.name} ads on ${best.wilaya} — ${(best.successRate * 100).toFixed(1)}% success rate`,
        description: `${best.wilaya} achieved ${(best.successRate * 100).toFixed(1)}% delivery success rate across ${best.orders} orders. This is among the strongest-performing regions for this merchant. Concentrating ad spend here maximises delivered revenue.`,
        reason: `${best.wilaya} outperforms this merchant's average delivery rate (${(m.deliverySuccessRate * 100).toFixed(1)}%) by ${((best.successRate - m.deliverySuccessRate) * 100).toFixed(1)} percentage points.`,
        businessImpact: `Increasing orders in ${best.wilaya} by 20% could generate an additional ${(revenue / 1000).toFixed(0)}K DZD in delivered revenue.`,
        estimatedSavingsDzd: 0,
        estimatedRevenueIncreaseDzd: revenue,
        confidenceScore: confidence,
        generatedAt: NOW,
        requiredDataSources: ["merchant_shipment_history"],
        recommendedActions: [
          { label: `Increase ad targeting in ${best.wilaya}`, description: `This wilaya has a ${(best.successRate * 100).toFixed(1)}% success rate — allocate more budget here.` },
          { label: "Create region-specific creatives", description: `Tailor ad content to ${best.wilaya} audience for better conversion.` },
        ],
        wilaya: best.wilaya,
      });
    }

    // Reduce recommendation for worst wilayas
    if (worstWilayas.length > 0) {
      const worst = worstWilayas[0];
      const signal = rateSignalStrength(worst.successRate, 0.5, WILAYA_AVOID_BAD);
      const confidence = calculateConfidence(worst.orders, signal);
      const savings = adPauseSavings(
        Math.round(worst.orders * (1 - worst.successRate)),
        m.avgBasketDzd,
      );
      recs.push({
        id: nextId(),
        merchantId: m.merchantId,
        merchantName: m.name,
        category: "advertising",
        type: "advertising_reduce",
        priority: worst.successRate < 0.20 ? "HIGH" : "MEDIUM",
        title: `Reduce ${m.name} ads in ${worst.wilaya} — only ${(worst.successRate * 100).toFixed(1)}% success rate`,
        description: `${worst.wilaya} delivered only ${(worst.successRate * 100).toFixed(1)}% of ${worst.orders} orders. The return/refusal rate is ${((1 - worst.successRate) * 100).toFixed(1)}%. Ad spend here is generating losses, not revenue.`,
        reason: `${worst.wilaya} underperforms this merchant's average delivery rate (${(m.deliverySuccessRate * 100).toFixed(1)}%) by ${((m.deliverySuccessRate - worst.successRate) * 100).toFixed(1)} percentage points.`,
        businessImpact: `Reducing ad spend in ${worst.wilaya} could save ${(savings / 1000).toFixed(0)}K DZD in avoided return costs.`,
        estimatedSavingsDzd: savings,
        estimatedRevenueIncreaseDzd: 0,
        confidenceScore: confidence,
        generatedAt: NOW,
        requiredDataSources: ["merchant_shipment_history"],
        recommendedActions: [
          { label: `Exclude ${worst.wilaya} from ad targeting`, description: "Remove this wilaya from ad geotargeting to stop generating unprofitable orders." },
          { label: "Investigate root cause", description: "High return rates in specific wilayas can indicate product-market mismatch or delivery infrastructure issues." },
        ],
        wilaya: worst.wilaya,
      });
    }
  }

  return recs;
}
